changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
    authors:
      - dependabot
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
        - new
    - title: Bug Fixes
      labels:
        - bug
        - fix
        - bugfix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Infrastructure
      labels:
        - ci
        - build
        - infra
    - title: Maintenance
      labels:
        - refactor
        - chore
        - maintenance
    - title: Other Changes
      labels:
        - "*"
